apiVersion: v1
kind: Service
metadata:
  name: iiisconnect-gateway
  namespace: weixu
  labels:
    app: iiisconnect-gateway
spec:
  type: ClusterIP
  selector:
    app: iiisconnect-gateway
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: proxy
    port: 3128
    targetPort: 3128
    protocol: TCP
